### ISSUE TITLE
Status of other database commands?

### ISSUE THREAD

**Issue by joewiz** [dizzzz/Mongrel#5]
Hi Dannes,

I got my first connection to MongoDB from eXist up and running!  Thanks so much for this tool!

The tutorial I followed for MongoDB was [The Little MongoDB Book](https://github.com/karlseguin/the-little-mongodb-book) (initially found via the iBooks store, but a newer edition covering MongoDB 2.6 is available as [PDF](http://openmymind.net/mongodb.pdf) and [epub](http://openmymind.net/mongodb.epub)), which explained how to use the "update" command, e.g.:

    db.unicorns.update({name: 'Roooooodles'}, {$set: {weight: 590}})

    db.hits.update({page: 'unicorns'}, {$inc: {hits: 1}}, true);

I don't see `update` in the list of available XQuery functions. This raises the question - what is the status of the implementation of other of MongoDB's database commands, as listed at http://docs.mongodb.org/manual/reference/command/?

Also, the wiki page on MongoDB examples mentions `mongodb:query()`, but I believe it should be `mongodb:find()`.  Didn't want to make this change without checking with you first.

Bravo!
Joe

**Comment by dizzzz** [comment]
Hi Joe, 

yes, some things are a bit rough yet (you are right on the name; started to use 'high-level' or 'descriptive' function names, but I'll match the java api as closely as possible, making explanation of the functions as easy as possible.

Currently studying how to wrap 'data base modifying commands' into xquery functions. I have good leads, in 'master' there are some more functions I think.

More important ... currently creating unit/integration tests for the functions. Should have done that before :-) with these .xql files the functionality will become more clear.

so.... yes, the main functions are 'read' and 'insert', update is coming soon (plus the aggregate and other functions)


thnx for the feedback, I appreciate !

regards

Dannes

**Comment by dizzzz** [comment]
@joewiz it should be possible to send js-queries via the eval() functions, to do the same.

**Comment by dizzzz** [comment]
update the documentation, thnx

**Comment by dizzzz** [comment]
@joewiz , I'll focus on the 'Query and Write Operation Commands' and 'Aggregation Commands' in the first place; I think the others are less relevant to have available in existdb ; as I said, I think it is possible to address missing functions using the javascript-eval/command functions

**Comment by joewiz** [comment]
@dizzzz Thanks!  This sounds like a reasonable strategy.  It could be a lot of work to duplicate the full API (constantly changing too), and all options can be executed through javascript-eval anyway.  Better to focus on a core set of features you (and the community) need.  Exciting, and thanks again!

**Comment by dizzzz** [comment]
Added the findAndModify() functions (limited set of parameters) https://github.com/dizzzz/Mongrel/pull/9

**Comment by joewiz** [comment]
Very nice!  Super useful.  Thanks!

**Comment by dizzzz** [comment]
the aggregation() feature is in place now too.... next step: map-reduce
